# Generated by Django 4.2.1 on 2023-06-08 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='primary_lang',
        ),
        migrations.RemoveField(
            model_name='data',
            name='secondary_lang',
        ),
    ]
